version: "2"

services:
    # web server
    php:
      build: ./build/php
      container_name: php-7.0-apache
      volumes:
        - ./src:/var/www/html
      ports:
        - 80:80 
      networks:
        - mynetwork
networks:
  mynetwork:
    driver: bridge
    ipam:
        config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1
              aux_addresses:
                php: 10.5.0.5 
                #mysql: 10.5.0.5
