version: "2"

services:
    # web server
    php:
      build: ./build/php
      container_name: php-7.0-apache
      volumes:
        - ./src:/var/www/html
      ports:
        - 80:80
      networks:
        MyNetwork:
            ipv4_address: 192.168.43.10
networks:
  MyNetwork:
    ipam:
      config:
        - subnet: 192.168.43.0/24
          ip_range: 192.168.43.0/24  
