version: "2"
services:
    # web server
    php:
      build: ./build/php
      container_name: php-7.0-apache
      volumes:
        - ./src:/var/www/html
    networks:
      static-network:
        ipv4_address: 172.20.128.2
      ports:
        - 80:80

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24
