version: "2"

services:
    # web server
    php:
      build: ./build/php
      container_name: php-7.0-apache
      volumes:
        - ./src:/var/www/html
      ports:
        - 80:80 
      networks:
        vpcbr:
            ipv4_address: 10.5.0.6
      environment:
        - SERVERNAME=example.local      
            
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
