version: "2"

services:
    # web server
    php:
      build: ./build/php
      container_name: php-7.0-apache
      volumes:
        - ./src:/var/www/html
      ports:
        - 80:80 
    networks:
      mynetwork:
        ipv4_address: 10.5.0.5
networks:
  mynetwork:
    ipam:
      driver: default
      config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
