version: "2"

services:
    # web server
    php:
      build: ./build/php
      container_name: php-7.0-apache
      volumes:
        - ./src:/var/www/html
      ports:
        - 80:80
    # MySQL
    mysql:
      image: mysql:5.7
      container_name: mysql
      volumes:
        - ./build/mysql:/docker-entrypoint-initdb.d
        - ./tmp/mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=isee01
        - MYSQL_ROOT_PASSWORD=password

    # phpMyAdmin
    pma:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - mysql:db
      ports:
        - 8080:80
