version: "2"
services:
    # web server
    php:
      build: ./build/php
      container_name: php-7.0-apache
      volumes:
        - ./src:/var/www/html
      networks:
        default:
            ipv4_address: 192.168.43.5
      ports:
        - 80:80

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 192.168.43.0/24
                  gateway: 192.168.43.1
