version: "2"
services:
    # web server
    php:
      build: ./build/php
      container_name: php-7.0-apache
      volumes:
        - ./src:/var/www/html
      networks:
        default:
            ipv4_address: 192.168.0.7
      ports:
        - 80:80
